######################################################################
# Automatically generated by qmake (3.0) Wed Oct 29 20:01:28 2014
######################################################################

TEMPLATE = app
TARGET = matrix-multiply
INCLUDEPATH += .

# Input
SOURCES += main.cpp
